---
- name: Update apt cache and install Docker and Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Ensure docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Clone the Authentik repository
  git:
    repo: https://github.com/goauthentik/authentik.git
    dest: /opt/authentik
    version: master

- name: Deploy production docker-compose file for Authentik
  template:
    src: docker-compose.yml.j2
    dest: /opt/authentik/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Authentik
