---
- name: Update apt cache and install QEMU Guest Agent
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: yes

- name: Ensure QEMU Guest Agent service is enabled and running
  service:
    name: qemu-guest-agent
    state: started
    enabled: yes
